from snakemake.utils import min_version
import pandas as pd
import os

min_version("6.10.0")


configfile: "config/config.yml"


# read sample sheet
samples = (
    pd.read_csv(config["samplesheet"], sep="\t", dtype={"sample": str})
    .set_index("sample", drop=False)
    .sort_index()
)

# ─────────────────────────────────────────────────────────────────────────────
# 1. Prep FASTQ file module
# ─────────────────────────────────────────────────────────────────────────────


# declare https://github.com/ZandvakiliLab/snakemake-prep-reads as a module
module prepreads:
    snakefile:
        github(
            "ZandvakiliLab/snakemake-prep-reads",
            path="workflow/Snakefile",
            branch="main",
        )
    config:
        config


# use all rules from https://github.com/ZandvakiliLab/snakemake-prep-reads
use rule * from prepreads as prepreads_*


# ─────────────────────────────────────────────────────────────────────────────
# 2. Alignment module
# ─────────────────────────────────────────────────────────────────────────────


# declare https://github.com/ZandvakiliLab/snakemake-align as a module
module align:
    snakefile:
        github(
            "ZandvakiliLab/snakemake-align", path="workflow/Snakefile", branch="main"
        )
    config:
        config


# use all rules from https://github.com/ZandvakiliLab/snakemake-align
use rule * from align exclude multiqc as align_*


# ─────────────────────────────────────────────────────────────────────────────
# 3. Module rule Modification
# ─────────────────────────────────────────────────────────────────────────────


use rule multiqc from prepreads as prepreads_multiqc with:
    input:
        lambda wc: prepreads.get_multiqc_input(wc) + align.get_multiqc_input(wc),


# ─────────────────────────────────────────────────────────────────────────────
# container definition (optional)
# ─────────────────────────────────────────────────────────────────────────────
containerized: "oras://ghcr.io/ZandvakiliLab/fastq-prep-and-align:latest"


# ─────────────────────────────────────────────────────────────────────────────
# 5. Default Target
# ─────────────────────────────────────────────────────────────────────────────


rule all:
    default_target: True
    input:
        "results/multiqc/multiqc_report.html",
        expand(
            "results/processed_alignment/cram/{sample}_{subset}.cram.crai",
            sample=samples.index,
            subset=list(
                config.get("mapping_postprocessing", {}).get("filter", {}).keys()
            ),
        ),
        "results/jbrowse/config.json",
